from __future__ import annotations

import argparse
import json
from pathlib import Path

from mpmath import mp

from pslq_templates import K0, row_to_jsonable


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build stabilized coordinate vectors from multiple precision runs.")
    parser.add_argument("inputs", nargs="+", help="JSON files generated by compute_sn.py at increasing precision.")
    parser.add_argument("--s-tol", type=float, default=1e-20)
    parser.add_argument("--l-tol", type=float, default=1e-20)
    parser.add_argument("--out", default="artifacts/stable_prefix.json")
    return parser.parse_args()


def load_rows(path: Path) -> dict[int, dict]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    rows = payload.get("rows") or payload.get("data") or []
    normalized: dict[int, dict] = {}
    for row in rows:
        s_n = row.get("S_n")
        log_s_n = row.get("log_S_n", row.get("L_n"))
        if s_n is None:
            continue
        if log_s_n is None:
            log_s_n = mp.nstr(mp.log(mp.mpf(s_n)), 50)
        normalized[int(row["n"])] = {
            **row,
            "S_n": s_n,
            "log_S_n": log_s_n,
        }
    return normalized


def main() -> None:
    args = parse_args()
    inputs = [Path(p) for p in args.inputs]
    datasets = [load_rows(p) for p in inputs]
    common = sorted(set.intersection(*(set(d.keys()) for d in datasets)))

    stable_rows = []
    stable_prefix_end = 0
    for n in common:
        s_vals = [mp.mpf(d[n]["S_n"]) for d in datasets]
        l_vals = [mp.mpf(d[n]["log_S_n"]) for d in datasets]

        s_spread = max(s_vals) - min(s_vals)
        l_spread = max(l_vals) - min(l_vals)
        stable = abs(s_spread) <= args.s_tol and abs(l_spread) <= args.l_tol

        item = row_to_jsonable(n, s_vals[-1])
        item.update(
            {
                "stable": bool(stable),
                "source_precisions": [Path(p).stem for p in inputs],
                "spread_S_n": mp.nstr(s_spread, 30),
                "spread_log_S_n": mp.nstr(l_spread, 30),
                "K0": mp.nstr(K0, 50),
            }
        )
        if stable and n == stable_prefix_end + 1:
            stable_prefix_end = n
            stable_rows.append(item)
        elif n <= stable_prefix_end + 1:
            break

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "metadata": {
            "stable_count": len(stable_rows),
            "stable_prefix_end": stable_prefix_end,
            "s_tol": args.s_tol,
            "l_tol": args.l_tol,
            "coord_names": ["S_n", "log_S_n", "S_n_minus_K0", "log_n"],
        },
        "stable_rows": stable_rows,
    }
    out_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print({"stable_count": len(stable_rows), "stable_prefix_end": stable_prefix_end, "out": str(out_path)})


if __name__ == "__main__":
    main()
